In [2]:
import numpy as np
import pandas as pd

tau = np.array([0.02, 0.03])
seedLoc=np.array([51, 51059, 51121])
emergenceDay=np.array([90, 120, 150])

combination=[(i, j, k) for i in tau for j in seedLoc for k in emergenceDay]

s='/project/biocomplexity/biosurveillance/EpiHiper/sampling/input.csv'

colNames=['tau1', 'seedLoc1', 'emergenceDay', 'repli', 'iterRepli', 'Bg', 'Bp', 'dayd', 'UFullPool', 'UVariant2', 'flag']
combine=pd.DataFrame(columns = colNames)
samplingName='randomWithOutMemoryExp5_tau_'
#samplingName='qDegreeWithMemoryadjustExp4_tau_'
inp=pd.read_csv(s)
for row in inp.itertuples():
    print(row[1])
    f='/project/biocomplexity/biosurveillance/EpiHiper/sampling/result23b/'+samplingName+str(row[2])+'_var2_1.4_seed2n_'+str(row[4])+'_seed2t_'+str(row[5])+'_bp_'+str(row[6])+'_bg_'+str(row[7])+'.csv'

    samplingCell=pd.read_csv(f)
    #print(list(samplingCell.columns))
    combine=combine.append(samplingCell)

f='/project/biocomplexity/biosurveillance/EpiHiper/postProcessing/combineSamplingResult/'+samplingName+'_rep_20.csv'
combine.to_csv(f, encoding='utf-8', index=False)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72

In [12]:
%debug

> <ipython-input-9-864fdb3d3894>(23)<module>()
     21     samplingCell=pd.read_csv(f)
     22     #print(list(samplingCell.columns))
---> 23     combine=combine.append(samplingCell)
     24
     25 f='/project/biocomplexity/biosurveillance/EpiHiper/postProcessing/combineSamplingResult/'+samplingName+'_rep_60.csv'

ipdb>  tau

array([0.02, 0.03])

ipdb>  n

In [13]:
combine

,tau1,seedLoc1,emergenceDay,repli,iterRepli,Bg,Bp,dayd,UFullPool,UVariant2,flag
0,0.02,51,90,1,1,15,10000,91,141,0,0
1,0.02,51,90,1,1,15,10000,92,125,0,0
2,0.02,51,90,1,1,15,10000,93,118,0,0
3,0.02,51,90,1,1,15,10000,94,111,0,0
4,0.02,51,90,1,1,15,10000,95,104,2,1
...,...,...,...,...,...,...,...,...,...,...,...
11995,0.00,0,0,0,0,0,0,0,0,0,0
11996,0.00,0,0,0,0,0,0,0,0,0,0
11997,0.00,0,0,0,0,0,0,0,0,0,0
11998,0.00,0,0,0,0,0,0,0,0,0,0
11999,0.00,0,0,0,0,0,0,0,0,0,0

In [6]:
%debug

> /sfs/qumulo/qhome/cbn7xr/pandas/_libs/parsers.pyx(674)pandas._libs.parsers.TextReader._setup_parser_source()

ipdb>  n